export const acquire_session_token_markdown = () => {
  return `
# Welcome To Your Third Challenge For Creating User Controlled Wallets

In this task, you will complete the third step of creating a user controlled wallet, which is to get the session token and encryption key.

Please note that, at this point, you should already have the User ID.

## What Are Session Token And Encryption Key?

A session token is a temporary credential that is generated by the Circle API for authenticating the user for subsequent requests to the API endpoints. A session token expires after a certain period of time or when the user logs out.

An encryption key is a secret value that is derived from the user's PIN or biometric data. It is used to encrypt and decrypt the user's private keys, which are needed to sign transactions and interact with smart contracts on the blockchain. The encryption key is never stored or transmitted by Circle, and it is also used to generate a challenge ID, which is a one-time code that is required to initialize the user's wallets.

This task will be done in the same manner as the previous ones.

- You will be updating the code in the folder \`~/src/app/api/acquire_session_token/route.js\`.
- Once you get the session token and encryption key, you will add them to your \`.env.local\` file under the names: \`NEXT_PUBLIC_USER_TOKEN\` and \`NEXT_PUBLIC_ENCRYPTION_KEY\`.
- Even though the session token and encryption key are temporary, the reason why you are adding them to your \`.env.local\` file is to make sure that at the end of the user-controlled-wallet section, in the \`.env.local\` file, you will have all the necessary information to create a user-controlled-wallet.
- You will upload the user token to the Risein platform.
`;
};

export const get_app_id_markdown = () => {
  return `
    # Welcome To Your First Challenge For Creating User Controlled Wallets

In this task, you will complete the first step of creating a user controlled wallet, which is to get the App ID.

Please note that, at this point, you should already have a Circle API key.

## What is APP ID?

An App ID is a unique identifier that is assigned to your application when you register it with Circle. It is used for various purposes, such as identification, configuration management, and API access. You can think of it as a digital passport for your application to interact with the Circle Platform and the Universal Community Wallet. 🛂

1. Now, go to the \`~/src/api/get_app_id/route.js\` file.
2. Copy and paste the code that you see on the screen. This will send an API call to Circle API and you will retrieve your App ID.
3. Click on the "Get ID" button to retrieve your App ID.
4. Finally, once you get your App ID, add this to your \`.env.local\` file under the name: \`NEXT_PUBLIC_APP_ID\` and submit your APP ID to Risein platform as your first task.`;
};
